### ISSUE TITLE
unsupported operation on the graphics display list

### ISSUE THREAD

**Issue by vnijs** [pmur002/gridgraphics#16]
It seems that capturing a dendrogram does not currently work as expected. See example code and warning below. FYI I initially posted this as https://github.com/thomasp85/patchwork/issues/134 but it seems the issue starts in gridGraphics

```
hc <- hclust(dist(USArrests), "ave")
gridGraphics::grid.echo(function() plot(hc))
```

```
Warning messages:
1: In FUN(X[[i]], ...) :
  unsupported operation on the graphics display list
2: In FUN(X[[i]], ...) :
  unsupported operation on the graphics display list
```

This is the image that is produced:

![image](https://user-images.githubusercontent.com/2998956/70087217-bc004c00-15c8-11ea-9b2d-bd245e276aec.png)

It should be:

![image](https://user-images.githubusercontent.com/2998956/70087247-cb7f9500-15c8-11ea-80fe-be2264583a13.png)

**Comment by pmur002** [comment]
You are correct!  Somehow that just got missed completely.  I have pushed a new version (0.4-0) that adds support.  Hope that does what you need.

**Comment by vnijs** [comment]
Awesome! Thanks @pmur002! Using  gridGraphics and patchwork the below now works.

```
hc <- hclust(dist(USArrests), "ave")
plot(hc)
plot_list <- list()
plot_list[[1]] <- ggplot(mtcars) +  geom_point(aes(mpg, disp)) 
plot_list[[2]] <- wrap_elements(~ plot(hc), clip = FALSE)
patchwork::wrap_plots(plot_list, ncol = 2)
```

![image](https://user-images.githubusercontent.com/2998956/70182936-b0c92100-1699-11ea-9564-59bcbb4fa1a4.png)
