### ISSUE TITLE
Is makeContext necessary while using makeContent?

### ISSUE THREAD

**Issue by Anirban166** [pmur002/gridgraphics#17]
Hi @pmur002 

I have a question:
When using a `makeContent` method for a grob class we define, is it a must to use a `makeContext` method for it as well?

For reference, I'm working on refactoring the [directlabels](https://github.com/tdhock/directlabels) codebase which currently uses a `drawDetails` method on a grob class named `dlgrob`, but it doesn't use a `preDrawDetails` and a corresponding `postDrawDetails` method.
Also, the sole purpose of using `makeContent` (instead of `drawDetails`) here is to make use of `grid.force`. It's one of my objectives as stated [here](https://github.com/rstats-gsoc/gsoc2021/wiki/directlabels-improvements), and [this plan](https://github.com/Anirban166/directlabels-improvements) (3rd point) is what I'll be going ahead with.

In the current [setup](https://github.com/tdhock/directlabels/blob/master/R/positioning.functions.R), `drawDetails.dlgrob` is called with the current ggplot/lattice panel as the current viewport. This is required in order to compute text size correctly via grid functions `convertX`/`convertY`. So I would like to know, will the current viewport be taken as the current panel while using `makeContent` as well? (then I suppose we don't have to use `makeContext`?)

**Comment by pmur002** [comment]
In general, no, a makeContext() is not a requirement.  The current viewport when makeContent() is called should be the current ggplot/lattice panel.

**Comment by Anirban166** [comment]
Gotcha! Thank you for confirming this.
