### ISSUE TITLE
Fails to Install in R 3.4.0

### ISSUE THREAD

**Issue by atclaus** [pmur002/gridgraphics#6]
Cannot load into R 3.4.0 on Ubuntu 16.04. Had trouble with rJava in 3.4.0 for xlsx as well, and the latest [dev there](https://github.com/dragua/xlsx/issues/83) seemed to help, not sure if it would here as well.

    > install.packages("gridGraphics",dependencies = TRUE)
    Installing package into ‘/usr/local/lib/R/site-library’
    (as ‘lib’ is unspecified)
    trying URL 'https://mirrors.nics.utk.edu/cran/src/contrib/gridGraphics_0.2.tar.gz'
    Content type 'application/x-gzip' length 64486 bytes (62 KB)
    ==================================================
    downloaded 62 KB

    * installing *source* package ‘gridGraphics’ ...
    ** package ‘gridGraphics’ successfully unpacked and MD5 sums checked
    ** R
    ** inst
    ** preparing package for lazy loading
    Error in system("convert --version", intern = TRUE, ignore.stderr = TRUE) :
      error in running command
    Error : unable to load R code in package ‘gridGraphics’
    ERROR: lazy loading failed for package ‘gridGraphics’
    * removing ‘/usr/local/lib/R/site-library/gridGraphics’

    The downloaded source packages are in
            ‘/tmp/Rtmpu5vMUL/downloaded_packages’
    Warning message:
    In install.packages("gridGraphics", dependencies = TRUE) :
      installation of package ‘gridGraphics’ had non-zero exit status

**Comment by pmur002** [comment]
The missing piece is ImageMagick.  Looks like you are on Linux(?), so should hopefully just be 'sudo apt-get install imagemagick' (or equivalent).  I am also in [discussion](https://github.com/pmur002/gridgraphics/issues/5) with the maintainer of the 'magick' package to make this dependency more robust/

**Comment by atclaus** [comment]
That does it. Thank you!
